### ISSUE TITLE
unable to send message , getting Error instead

### ISSUE THREAD

**Issue by mator** [nopp/alertmanager-webhook-telegram#10]
getting error while trying to send this message 
```
echo "{'status': 'resolved', 'groupLabels': {'alertname': 'NodeFilesystemUsage'}, 'commonAnnotations': {'summary': 'Free space in /dev/xvda1 from xxx:9100 is less than 30% (current value is: 25.958346702725827)'}, 'alerts': [{'status': 'resolved', 'labels': {'fstype': 'xfs', 'instance': 'xxx:9100', 'job': 'Node_Exporter', 'alertname': 'NodeFilesystemUsage', 'device': '/dev/xvda1', 'mountpoint': '/'}, 'endsAt': '2019-12-18T10:18:14.7054982Z', 'generatorURL': 'http://xxx/graph?zzz', 'fingerprint': '18d63651e98d6f9b', 'startsAt': '2019-12-18T10:15:44.7054982Z', 'annotations': {'summary': 'Free space in /dev/xvda1 from xxx:9100 is less than 30% (current value is: 25.958346702725827)'}}], 'version': '4', 'receiver': 'telebot', 'externalURL': 'http://xxx:9093', 'commonLabels': {'fstype': 'xfs', 'instance': 'xxx:9100', 'job': 'Node_Exporter', 'alertname': 'NodeFilesystemUsage', 'device': '/dev/xvda1', 'mountpoint': '/'}}" | 
curl -X POST -d '@-' http://user:password@127.0.0.1:9119/alert
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
```

docker logs:
```
[2019-12-19 09:05:49,145] ERROR in app: Exception on /alert [POST]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1951, in full_dispatch_r
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1820, in handle_user_exc
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1949, in full_dispatch_r
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/alertmanager-webhook-telegram/flaskAlert.py", line 21, in postAlertmanager
    content = json.loads(request.get_data())
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting property name: line 1 column 2 (char 1)
```

**Comment by nopp** [comment]
Hup, your json is invalid my friend :)

**Comment by mator** [comment]
Thanks. Checked with random google 'json checker', (instead of command line `jq` ), and it is indeed a bit wrong JSON. Thanks again.

**Comment by mator** [comment]
@nopp 

can we please somehow debug (investigate) wrong JSON issue with alertmanager and webhook telegram? Guys from alertmanager [suggest](https://github.com/prometheus/alertmanager/issues/2172) that the issue is in your code.

**Comment by mator** [comment]
@nopp 

this is a sample Output.txt (incorrect json):

```
# cat Output.txt
{u'status': u'resolved', u'groupLabels': {u'alertname': u'EndpointDown'}, u'groupKey': u'{}:{alertname="EndpointDown"}', u'commonAnnotations': {u'summary': u'HTTP endpoint http://host1:8890/check is down'}, u'alerts': [{u'status': u'resolved', u'labels': {u'instance': u'http://host1:8890/check', u'job': u'blackbox', u'severity': u'critical', u'alertname': u'EndpointDown'}, u'endsAt': u'2020-01-27T12:44:29.7054982Z', u'generatorURL': u'http://prometheus:9090/graph?g0.expr=probe_success+%3D%3D+0&g0.tab=1', u'fingerprint': u'e9339b1de0ed2c47', u'startsAt': u'2020-01-27T12:42:44.7054982Z', u'annotations': {u'summary': u'HTTP endpoint http://host1:8890/check is down'}}], u'version': u'4', u'receiver': u'telegram-bot', u'externalURL': u'http://prometheus:9093', u'commonLabels': {u'instance': u'http://host1:8890/check', u'job': u'blackbox', u'severity': u'critical', u'alertname': u'EndpointDown'}}
```

this is tcpdump on port (_correct json_):
```

# tcpdump -n -i 5 -A port 9119
...
Host: 127.0.0.1:9119
User-Agent: Alertmanager/0.20.0
Content-Length: 886
Content-Type: application/json

{"receiver":"telegram-bot","status":"firing","alerts":[{"status":"firing","labels":{"alertname":"EndpointDown","instance":"http://host1:8890/check","job":"blackbox","severity":"critical"},"annotations":{"summary":"HTTP endpoint http://host1:8890/check is down"},"startsAt":"2020-01-27T12:42:44.7054982Z","endsAt":"0001-01-01T00:00:00Z","generatorURL":"http://prometheus:9090/graph?g0.expr=probe_success+%3D%3D+0\u0026g0.tab=1","fingerprint":"e9339b1de0ed2c47"}],"groupLabels":{"alertname":"EndpointDown"},"commonLabels":{"alertname":"EndpointDown","instance":"http://host1:8890/check","job":"blackbox","severity":"critical"},"commonAnnotations":{"summary":"HTTP endpoint http://host1:8890/check is down"},"externalURL":"http://prometheus:9093","version":"4","groupKey":"{}:{alertname=\"EndpointDown\"}"}
```

**Comment by amcgregor** [comment]
```
echo "{'status': 'resolved', …
```

You aren't submitting [JSON](https://www.json.org/json-en.html).  If you see single quotes, it's not JSON, as JSON mandates (requires) use of double quotes for all string literals.  (Seems to have been noticed, but worth pointing out very explicitly again.)

```
# cat Output.txt
{u'status': u'resolved', …
```

**Also not JSON.**  The `u` prefixes hint strongly that this is the result of a [`repr`](https://docs.python.org/2.7/library/functions.html#func-repr) call, possibly made automatically by attempting to run the parsed JSON result through [`print`](https://docs.python.org/2/reference/simple_stmts.html#print).  **Remember:** just because curly braces are involved does **not** make the data JSON.

~~Not shown: how `Output.txt` is being generated.  I'm fairly certain it's **NOT** the result of a `json.dump` or `json.dumps` call, but due to REPR use, the result of printing the loaded dictionary object.~~ carc1n0gen on IRC pointed out how it's being generated, and it is, in fact, being generated incorrectly: https://github.com/nopp/alertmanager-webhook-telegram/blob/a76c0cbc24cdbb8acc376356f99ebbbfd6cecd95/flaskAlert.py#L23 — the `.format` call will call `repr()` over the argument passed in, utilized this way.

For the initial problem: submit actual JSON data.  For diagnostics, be absolutely careful how you generate output, and how you interpret it.  `print(some_dict)` JSON does not make.  An MCVE ([minimal, complete, verifiable example](https://stackoverflow.com/help/mcve)) needs to include how you are generating your diagnostic output, too.

**Comment by mator** [comment]
sample JSON which validates over "google random JSON parser" http://json.parser.online.fr/  , but fails with `json.loads()` 
```
js = '{"receiver":"telegram-bot","status":"firing","alerts":[{"status":"firing","labels":{"alertname":"EndpointDown","instance":"http://webhost/","job":"blackbox","severity":"critical"},"annotations":{"summary":"HTTP endpoint http://webhost/ is down"},"startsAt":"2020-01-27T12:42:44.7054982Z","endsAt":"0001-01-01T00:00:00Z","generatorURL":"http://prometheus/graph?g0.expr=probe_success+%3D%3D+0\u0026g0.tab=1","fingerprint":"e9339b1de0ed2c47"}],"groupLabels":{"alertname":"EndpointDown"},"commonLabels":{"alertname":"EndpointDown","instance":"http://webhost","job":"blackbox","severity":"critical"},"commonAnnotations":{"summary":"HTTP endpoint http://webhost/ is down"},"externalURL":"http://prometheus","version":"4","groupKey":"{}:{alertname=\"EndpointDown\"}"}'
```

**Comment by amcgregor** [comment]
@mator Escaping failure.

> `'… "{}:{alertname=\"EndpointDown\"}"}'`

The `\` escaping there is escaping the quotes.  Not producing a literal `\` for the JSON parser to see.  (Essentially `\"` → `"`.  No escaping.)  You'll need those escapes to be `\\`, e.g. `\\"`.  (Validation may appear to succeed as you are copying the inner portion of the string, not evaluating the string and printing it, which would make the transformation obvious.)

Edited to add, to be extremely clear:

```
>>> js = '{"receiver":"telegram-bot","status":"firing","alerts":[{"status":"firing","labels":{"alertname":"EndpointDown","instance":"http://webhost/","job":"blackbox","severity":"critical"},"annotations":{"summary":"HTTP endpoint http://webhost/ is down"},"startsAt":"2020-01-27T12:42:44.7054982Z","endsAt":"0001-01-01T00:00:00Z","generatorURL":"http://prometheus/graph?g0.expr=probe_success+%3D%3D+0\u0026g0.tab=1","fingerprint":"e9339b1de0ed2c47"}],"groupLabels":{"alertname":"EndpointDown"},"commonLabels":{"alertname":"EndpointDown","instance":"http://webhost","job":"blackbox","severity":"critical"},"commonAnnotations":{"summary":"HTTP endpoint http://webhost/ is down"},"externalURL":"http://prometheus","version":"4","groupKey":"{}:{alertname=\"EndpointDown\"}"}'

>>> print(js[-40:])
oupKey":"{}:{alertname="EndpointDown"}"}
                       ^            ^

>>> js = '{"receiver":"telegram-bot","status":"firing","alerts":[{"status":"firing","labels":{"alertname":"EndpointDown","instance":"http://webhost/","job":"blackbox","severity":"critical"},"annotations":{"summary":"HTTP endpoint http://webhost/ is down"},"startsAt":"2020-01-27T12:42:44.7054982Z","endsAt":"0001-01-01T00:00:00Z","generatorURL":"http://prometheus/graph?g0.expr=probe_success+%3D%3D+0\u0026g0.tab=1","fingerprint":"e9339b1de0ed2c47"}],"groupLabels":{"alertname":"EndpointDown"},"commonLabels":{"alertname":"EndpointDown","instance":"http://webhost","job":"blackbox","severity":"critical"},"commonAnnotations":{"summary":"HTTP endpoint http://webhost/ is down"},"externalURL":"http://prometheus","version":"4","groupKey":"{}:{alertname=\\"EndpointDown\\"}"}'

>>> print(js[-40:])
pKey":"{}:{alertname=\"EndpointDown\"}"}
```

**Comment by nopp** [comment]
Here we go ....

**Comment by iliadpmi** [comment]
https://github.com/nopp/alertmanager-webhook-telegram/blob/a76c0cbc24cdbb8acc376356f99ebbbfd6cecd95/flaskAlert.py#L21

`content = json.loads(str(request.get_data()).replace('\\"',"'"))`

**Comment by iliadpmi** [comment]
https://github.com/nopp/alertmanager-webhook-telegram/blob/a76c0cbc24cdbb8acc376356f99ebbbfd6cecd95/flaskAlert.py#L40

`message += """\n\n"""+str(alert['annotations'])+""""""`

It's allows you to ignore the keys values in alert['annotations'] dict - 'description' or 'summary' or whatever

https://github.com/nopp/alertmanager-webhook-telegram/blob/a76c0cbc24cdbb8acc376356f99ebbbfd6cecd95/flaskAlert.py#L44

`except Exceptions as e:`

https://github.com/nopp/alertmanager-webhook-telegram/blob/a76c0cbc24cdbb8acc376356f99ebbbfd6cecd95/flaskAlert.py#L45
 ` bot.sendMessage(chat_id=chatID, text="Error: "+str(e))`

**Comment by nopp** [comment]
Hi guys, I broked my left hand, I'll need 40 days to back to work .... so, until this, I can't code anything.
