### ISSUE TITLE
Broken container image

### ISSUE THREAD

**Issue by yangm97** [nopp/alertmanager-webhook-telegram#14]
Running with the same flags as the README. Got:

```
admin user is [redacted]
password is set (not visible)
bottoken is set (not visible)
chatid is [redacted]
sed: flaskAlert.py: No such file or directory
sed: flaskAlert.py: No such file or directory
sed: flaskAlert.py: No such file or directory
sed: flaskAlert.py: No such file or directory
[2020-03-27 15:40:11 +0000] [10] [INFO] Starting gunicorn 19.10.0
[2020-03-27 15:40:11 +0000] [10] [INFO] Listening at: http://0.0.0.0:9119 (10)
[2020-03-27 15:40:11 +0000] [10] [INFO] Using worker: sync
[2020-03-27 15:40:11 +0000] [13] [INFO] Booting worker with pid: 13
[2020-03-27 15:40:11 +0000] [13] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/gunicorn/arbiter.py", line 586, in spawn_worker
    worker.init_process()
  File "/usr/lib/python2.7/site-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
  File "/usr/lib/python2.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/usr/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/lib/python2.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
ImportError: No module named flaskAlert
[2020-03-27 15:40:11 +0000] [13] [INFO] Worker exiting (pid: 13)
[2020-03-27 15:40:11 +0000] [10] [INFO] Shutting down: Master
[2020-03-27 15:40:11 +0000] [10] [INFO] Reason: Worker failed to boot.
```

**Comment by nopp** [comment]
solved.
