### ISSUE TITLE
invalid syntax error

### ISSUE THREAD

**Issue by mator** [nopp/alertmanager-webhook-telegram#20]
Hello!

Built a new image, ran it, getting error:
```
03a638c14e58[1541]: admin user is xxx
03a638c14e58[1541]: password is set (not visible)
03a638c14e58[1541]: bottoken is set (not visible)
03a638c14e58[1541]: chatid is zzz
03a638c14e58[1541]: [2021-03-09 09:56:59 +0000] [10] [INFO] Starting gunicorn 19.10.0
03a638c14e58[1541]: [2021-03-09 09:56:59 +0000] [10] [INFO] Listening at: http://0.0.0.0:9119 (10)
03a638c14e58[1541]: [2021-03-09 09:56:59 +0000] [10] [INFO] Using worker: sync
03a638c14e58[1541]: [2021-03-09 09:56:59 +0000] [12] [INFO] Booting worker with pid: 12
03a638c14e58[1541]: [2021-03-09 09:56:59 +0000] [12] [ERROR] Exception in worker process
03a638c14e58[1541]: Traceback (most recent call last):
03a638c14e58[1541]:   File "/usr/lib/python2.7/site-packages/gunicorn/arbiter.py", line 586, in spawn_worker
03a638c14e58[1541]:     worker.init_process()
03a638c14e58[1541]:   File "/usr/lib/python2.7/site-packages/gunicorn/workers/base.py", line 135, in init_process
03a638c14e58[1541]:     self.load_wsgi()
03a638c14e58[1541]:   File "/usr/lib/python2.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
03a638c14e58[1541]:     self.wsgi = self.app.wsgi()
03a638c14e58[1541]:   File "/usr/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
03a638c14e58[1541]:     self.callable = self.load()
03a638c14e58[1541]:   File "/usr/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
03a638c14e58[1541]:     return self.load_wsgiapp()
03a638c14e58[1541]:   File "/usr/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
03a638c14e58[1541]:     return util.import_app(self.app_uri)
03a638c14e58[1541]:   File "/usr/lib/python2.7/site-packages/gunicorn/util.py", line 350, in import_app
03a638c14e58[1541]:     __import__(module)
03a638c14e58[1541]:   File "/alertmanager-webhook-telegram/flaskAlert.py", line 1, in <module>
03a638c14e58[1541]:     import telegram, json, logging
03a638c14e58[1541]:   File "/usr/lib/python2.7/site-packages/telegram/__init__.py", line 21, in <module>
03a638c14e58[1541]:     from .base import TelegramObject
03a638c14e58[1541]:   File "/usr/lib/python2.7/site-packages/telegram/base.py", line 42
03a638c14e58[1541]:     _id_attrs: Tuple[Any, ...] = ()
03a638c14e58[1541]:              ^
03a638c14e58[1541]: SyntaxError: invalid syntax
03a638c14e58[1541]: [2021-03-09 09:56:59 +0000] [12] [INFO] Worker exiting (pid: 12)
03a638c14e58[1541]: [2021-03-09 09:56:59 +0000] [10] [INFO] Shutting down: Master
03a638c14e58[1541]: [2021-03-09 09:56:59 +0000] [10] [INFO] Reason: Worker failed to boot.
```

**Comment by nopp** [comment]
Use python3.
